### ISSUE TITLE
Ueli update to version 7.0.1 needed

### ISSUE THREAD

**Issue by neikei** [TimB87/choco-repo#1]
Hey TimB87,

in ueli version 7.0.0 was a bug which creates a lot of powershell processes and causes memory leaks, (Issue https://github.com/oliverschwendener/ueli/issues/71)

Can you update the ueli version to 7.0.1 for the chocolatey installation?

Best regards and thanks for the great project. :+1:

**Comment by TimB87** [comment]
Hi neikei,

I am on my vacation and I am not having a windows machine with me. It will be updated on the 17th. Sorry for the inconvenience this may cause!

Best regards

**Comment by oliverschwendener** [comment]
Would it be possible to include this repo into the original ueli repo? So I can update the choco stuff everytime i make a new update. What do you think?

**Comment by TimB87** [comment]
You can take over the choco package, there is no problem with that: https://chocolatey.org/docs/package-triage-process#are-you-a-software-vendor
But if you decide not to, I'll update the package next Monday.

**Comment by oliverschwendener** [comment]
I don't want to take over your choco package, I just thinkt it would be better if everything was in a central place. What if you include your work into my repo, for example in a separate `choco` folder, and every time I release a new version I can update the choco stuff too. What do you think?

**Comment by TimB87** [comment]
> and every time I release a new version I can update the choco stuff too. What do you think?

To update the choco stuff you would need a key to push the nupkg to the choco repository. That's why I thought you wanted to overtake the package. My github repo just contains the source to generate a nupkg file which then again is hosted in the official choco repo to install/update the package.

In the case that you want to give me access to your repository containing a choco package I would still need access to a Windows 10 instance to generate a nupkg and push it to the choco server. So I think this would make no difference to our situation now.

**Comment by oliverschwendener** [comment]
Ok then I think we leave it as is.

**Comment by neikei** [comment]
Exciting discussion! Maybe it makes sense not to roll out a major update (x.0.0) until a minor update (x.1.0) or patch (x.0.1) has been released to avoid this kind of problem.

Just a quick note: version 7.1.0 has also been released 5 days ago

**Comment by oliverschwendener** [comment]
@neikei This makes absolutely no sense to me. Every version has to be rolled out in my opinion. Not every major release has critical bugs and not every patch version is absolutely bug-free.

**Comment by neikei** [comment]
@oliverschwendener that's right. It was just an idea, because some companies are following a roll out strategy like that, because a major update brings larger changes and these changes can contain more bugs.

Anyway, this kind of bugfix should of course be rolled out quickly.

**Comment by oliverschwendener** [comment]
> It was just an idea, because some companies are following a roll out strategy like that, because a major update brings larger changes and these changes can contain more bugs.

This strategy is used when using software and not when making it available. Chocolatey is a package repository which should contain **all** released versions of a software. It is up to the user if he wants to update to the latest version or wait for a *more stable* release.

**Comment by TimB87** [comment]
#1f8cdc6
done and closed
